spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: kiril
    password: kiril
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yml

logging:
  level:
    root: INFO
    com.example: DEBUG
  file:
    name: logs/user-subscription.log
